services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 5173:5173
    volumes:
      - .:/app
    networks:
      - greenhouseguardian

networks:
  greenhouseguardian:
    external: true
