- name: install nginx
  apt: name=nginx state=latest

- name: copy nginx config
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    owner: www-data
    group: www-data
    mode: 0644

- name: enable nginx site
  file:
    src: /etc/nginx/sites-available/default
    path: /etc/nginx/sites-enabled/default
    state: link
  notify:
    - nginx restart

- name: start nginx
  service:
    name: nginx
    state: started
