#Create deploy directory
- name: Create deploy directory
  file:
    path: "{{ frontend_deploy_dir }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0755

# clone git repository
- name: Clone api repository
  git:
    repo: "{{ greenhouse_guardian_repo }}"
    dest: "{{ frontend_deploy_dir }}"
    accept_hostkey: yes
    clone: yes
    update: yes
    version: "{{ branch_name | default('main', true) }}"

#Change ownership of frontend_deploy_dir
- name: Change ownership of frontend_deploy_dir
  file:
    path: "{{ frontend_deploy_dir }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    state: directory
    recurse: yes

# copy .env file
- name: Copy .env file
  template:
    src: .env.j2
    dest: "{{ frontend_deploy_dir }}/frontend/.env"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0660

- name: Tear down existing services
  docker_compose:
    project_src: "{{ frontend_deploy_dir }}/frontend"
    files:
      - docker-compose-prod.yml
    state: absent

# Start deploy.compose docker service
- name: Start deploy.compose docker service
  #become_user: "{{ docker_user }}"
  docker_compose:
    project_src: "{{ frontend_deploy_dir }}/frontend"
    files:
      - docker-compose-prod.yml
    state: present
    build: yes
