#Create deploy directory
- name: Create deploy directory
  file:
    path: "{{ api_deploy_dir }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0755

# clone git repository
- name: Clone api repository
  git:
    repo: "{{ greenhouse_guardian_repo }}"
    dest: "{{ api_deploy_dir }}"
    accept_hostkey: yes
    clone: yes
    update: yes
    version: "{{ branch_name | default('main', true) }}"

#Change ownership of api_deploy_dir
- name: Change ownership of api_deploy_dir
  file:
    path: "{{ api_deploy_dir }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    state: directory
    recurse: yes

# copy .env file
- name: Copy .env file
  template:
    src: .env.j2
    dest: "{{ api_deploy_dir }}/api/.env"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0640

- name: Tear down existing services
  docker_compose:
    project_src: "{{ api_deploy_dir }}/api"
    files:
      - docker-compose-prod.yml
    state: absent

# Start docker-compose-prod.yml docker service
- name: Start docker-compose-prod.yml docker service
  # become_user: "{{ docker_user }}"
  docker_compose:
    project_src: "{{ api_deploy_dir }}/api"
    build: yes
    files:
      - docker-compose-prod.yml
    state: present
