# Generated by Django 5.0.4 on 2024-04-06 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guardian", "0001_initial"),
        ("knox", "0008_remove_authtoken_salt"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="device_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="knox.authtoken",
            ),
        ),
    ]
