# Generated by Django 5.0.4 on 2024-04-07 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guardian", "0003_remove_device_humidity_limit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhook_type",
                    models.IntegerField(
                        choices=[(1, "Discord")], verbose_name="Webhook Type"
                    ),
                ),
                ("url", models.URLField(verbose_name="Webhook URL")),
                (
                    "message_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Prefix to add to messages. Useful for adding @everyone or similar",
                        max_length=255,
                        null=True,
                        verbose_name="Message Prefix",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
            },
        ),
    ]
