# Generated by Django 5.0.4 on 2024-04-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guardian", "0005_webhook_last_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="webhook_type",
            field=models.IntegerField(
                choices=[(1, "Discord")], default=1, verbose_name="Webhook Type"
            ),
        ),
    ]
