version: "3.7"

services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "greenhouse_guadian"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"

    volumes:
      - my-db:/var/lib/mysql
    networks:
      - greenhouseguardien

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8090:80
    environment:
      PMA_HOST: "db"
      MYSQL_ROOT_PASSWORD: "password"
      PMA_USER: "root"
      PMA_PASSWORD: "password"
    networks:
      - greenhouseguardien

  web:
    build: .
    ports:
      - "8080:80"
      - "3456:3000"
    expose:
      - 80
    restart: unless-stopped
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      SECRET_KEY: "super_secret"
      MYSQL_HOST: "db"
      MYSQL_DATABASE: "greenhouse_guadian"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      ENVIRONMENT: "dev"

    volumes:
      - ./src/:/app/web/.
    networks:
      - greenhouseguardien

volumes:
  my-db:

networks:
  greenhouseguardien:
      external: false
      name: greenhouseguardian
